cache:
  directories:
  - node_modules # cache node_module
language: node_js # set language to node_js
node_js:
  7 # use node version 7
branches:
  only:
    - master # auto build and deploy in only master branch
script: # run after installed
  - npm install # install node module
  - npm run build # build project
